name: Add contributors to README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        with:
          use_username: true
          auto_detect_branch_protection: false
        env:
          GITHUB_TOKEN: ${{ secrets.ACES_BOT_FULL }}
          
