name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.ACES_BOT_FULL }}
        issue-message: "Thank you for working on this issue. Please go through the description in README.md and CONTRIBUTING.md first"
        pr-message: "Seems like this is your first PR in this repository. Please ensure that your PR follows the guidelines in CONTRIBUTING.md"
